# Install library

In [ ]:
!pip install pandas
!pip install openpyxl
!pip install gensim
!pip install SPARQLWrapper
!pip install xlrd==1.2.0
!pip install nltk
!pip install python-crfsuite

# Import library

In [1]:
import sys
import re
import pandas as pd
import numpy as np
from gensim.models import FastText
from gensim.models import KeyedVectors
from SPARQLWrapper import SPARQLWrapper, JSON
import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tag import CRFTagger
from collections import Counter
import pickle

stopword_set = set(stopwords.words('indonesian'))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


# Read data

In [2]:
# sample data

path = '../example-data/'
df_prof = pd.read_excel(path + 'df_structured.xlsx')
df_prof.info()
display(df_prof.head())

df_tweet = pd.read_csv(path + 'ridwankamil.csv')
df_tweet = df_tweet.drop_duplicates(subset=['tweet'])
df_tweet = df_tweet.sort_values(by='created_at', ascending=False)
df_tweet.info()
df_tweet.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 14 columns):
profile_background_color        1 non-null int64
profile_link_color              1 non-null object
profile_sidebar_border_color    1 non-null object
profile_sidebar_fill_color      1 non-null object
profile_text_color              1 non-null object
bio                             1 non-null object
name                            1 non-null object
username                        1 non-null object
followers                       1 non-null int64
friends_count                   1 non-null int64
listed_count                    1 non-null int64
favourites_count                1 non-null int64
statuses_count                  1 non-null int64
protected                       1 non-null bool
dtypes: bool(1), int64(6), object(7)
memory usage: 185.0+ bytes


profile_background_color profile_link_color profile_sidebar_border_color  \
0                    352726             D02B55                       829D5E   

  profile_sidebar_fill_color profile_text_color  \
0                     99CC33             3E4415   

                                                 bio          name  \
0  Governor of West Java. Broadcaster of Daily Ha...  Ridwan Kamil   

      username  followers  friends_count  listed_count  favourites_count  \
0  ridwankamil    4974848           2842          1547             22037   

   statuses_count  protected  
0           43924      False

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60 entries, 0 to 59
Data columns (total 36 columns):
id                 60 non-null int64
conversation_id    60 non-null int64
created_at         60 non-null object
date               60 non-null object
time               60 non-null object
timezone           60 non-null int64
user_id            60 non-null int64
username           60 non-null object
name               60 non-null object
place              0 non-null float64
tweet              60 non-null object
language           60 non-null object
mentions           60 non-null object
urls               60 non-null object
photos             60 non-null object
replies_count      60 non-null int64
retweets_count     60 non-null int64
likes_count        60 non-null int64
hashtags           60 non-null object
cashtags           60 non-null object
link               60 non-null object
retweet            60 non-null bool
quote_url          0 non-null float64
video              60 non-null i

id      conversation_id                created_at  \
0  1545938039058604032  1545937935606116352  2022-07-10 09:08:45 WITA   
1  1545937935606116352  1545937935606116352  2022-07-10 09:08:20 WITA   
2  1545371884703072256  1545371884703072256  2022-07-08 19:39:03 WITA   
3  1544966777628925952  1544966764001640449  2022-07-07 16:49:18 WITA   
4  1544966767956869120  1544966764001640449  2022-07-07 16:49:16 WITA   

         date      time  timezone   user_id     username          name  place  \
0  2022-07-10  09:08:45       800  80323736  ridwankamil  Ridwan Kamil    NaN   
1  2022-07-10  09:08:20       800  80323736  ridwankamil  Ridwan Kamil    NaN   
2  2022-07-08  19:39:03       800  80323736  ridwankamil  Ridwan Kamil    NaN   
3  2022-07-07  16:49:18       800  80323736  ridwankamil  Ridwan Kamil    NaN   
4  2022-07-07  16:49:16       800  80323736  ridwankamil  Ridwan Kamil    NaN   

     ...     geo source user_rt_id user_rt retweet_id  reply_to  retweet_date  \
0    ...     NaN    NaN        NaN     NaN        NaN        []           NaN   
1    ...     NaN    NaN        NaN     NaN        NaN        []           NaN   
2    ...     NaN    NaN        NaN     NaN        NaN        []           NaN   
3    ...     NaN    NaN        NaN     NaN        NaN        []           NaN   
4    ...     NaN    NaN        NaN     NaN        NaN        []           NaN   

   translate trans_src trans_dest  
0        NaN       NaN        NaN  
1        NaN       NaN        NaN  
2        NaN       NaN        NaN  
3        NaN       NaN        NaN  
4        NaN       NaN        NaN  

[5 rows x 36 columns]

In [13]:
# embedding model

path = '../embedding-model/'
ft = FastText.load_fasttext_format(path + 'fasttext.4B.id.300.epoch5.uncased.bin')
print(ft.wv[''])
ft_mei = FastText.load_fasttext_format(path + 'Fastext_model_tweet.bin')
print(ft_mei.wv[''])
w2v = KeyedVectors.load_word2vec_format(path + 'Word2Vec_400dim.txt', binary=False)
print(w2v['tes'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `load_fasttext_format` (use load_facebook_vectors (to use pretrained embeddings) or load_facebook_model (to continue training with the loaded full model, more RAM) instead).
  """


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: Call to deprecated `load_fasttext_format` (use load_facebook_vectors (to use pretrained embeddings) or load_facebook_model (to continue training with the loaded full model, more RAM) instead).
  import sys


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[ 5.475320e-01  3.569620e-01  3.962630e-01  2.167800e-02  4.917240e-01
 -5.828770e-01 -8.620200e-02  1.288480e-01  1.411340e-01 -7.269750e-01
  1.936090e-01  2.455980e-01  6.152400e-01 -3.042470e-01  1.783400e-02
 -3.934620e-01 -7.398300e-02 -3.880390e-01 -2.992310e-01 -3.117000e-02
  6.558350e-01 -6.021780e-01 -5.703900e-02  9.584700e-02  9.898300e-02
  1.169330e-01  8.250230e-01 -1.138290e-01 -2.305680e-01  8.036200e-01
  1.045630e-01 -5.149500e-02  3.153600e-01  1.885720e-01  2.469950e-01
  9.055360e-01  7.023960e-01  7.139110e-01  5.527090e-01  6.475150e-01
 -5.743880e-01  4.415870e-01  3.981350e-01  6.268070e-01  1.545900e-02
  5.637250e-01 -2.343790e-01 -5.336450e-01 -6.465700e-0

In [14]:
# vectorizer

path = '../vectorizer/'
bio_feat_bow_vectorizer = pickle.load(open(path + 'bio_feat_bow_vec.pickle', 'rb'))
bio_feat_bow_stop_vectorizer = pickle.load(open(path + 'bio_feat_bow_stop_vec.pickle', 'rb'))

name_feat_ia_vectorizer = pickle.load(open(path + 'name_feat_ia_vec.pickle', 'rb'))
name_feat_ib_vectorizer = pickle.load(open(path + 'name_feat_ib_vec.pickle', 'rb'))
name_feat_ic_first_vectorizer = pickle.load(open(path + 'name_feat_ic_first_vec.pickle', 'rb'))
name_feat_ic_middle_vectorizer = pickle.load(open(path + 'name_feat_ic_middle_vec.pickle', 'rb'))
name_feat_ic_last_vectorizer = pickle.load(open(path + 'name_feat_ic_last_vec.pickle', 'rb'))

username_feat_bow_vectorizer = pickle.load(open(path + 'username_feat_bow_vec.pickle', 'rb'))
username_feat_char_vectorizer = pickle.load(open(path + 'username_feat_char_vec.pickle', 'rb'))

tweet_feat_bow_vectorizer = pickle.load(open(path + 'tweet_feat_bow_vec.pickle', 'rb'))
tweet_feat_bow_stop_vectorizer = pickle.load(open(path + 'tweet_feat_bow_stop_vec.pickle', 'rb'))

In [13]:
# crf tagger

path = '../misc/'
ct = CRFTagger()
ct.set_model_file(path + 'all_indo_man_tag_corpus_model.crf.tagger')

# emoticon

f_open = open(path + 'EMOTICON.txt', 'r')
emoticons = f_open.read().split('\n')
f_open.close()

# Function

In [5]:
def get_wikidata_dict(endpoint_url, query):
    user_agent = 'WDQS-example Python/%s.%s' % (sys.version_info[0], sys.version_info[1])
    sparql = SPARQLWrapper(endpoint_url, agent=user_agent)
    sparql.setQuery(query)
    sparql.setReturnFormat(JSON)
    return sparql.query().convert()

def get_name_tokens(df, gender):
    df_temp = df[df.gender == gender]
    arr_res = []
    for d in df_temp['nama']:
        tokens = nltk.word_tokenize(d)
        tokens = [t.lower() for t in tokens]
        arr_res = arr_res + tokens
    return list(set(arr_res))

def get_vec(vectorizer, arr_text):
    return vectorizer.transform(arr_text).toarray()

# Main

## Color

In [17]:
# extraction

color_feat = []
color_feat_abl_pbc = []
color_feat_abl_plc = []
color_feat_abl_psbc = []
color_feat_abl_psfc = []
color_feat_abl_ptc = []

color_cols = [
    'profile_background_color',
    'profile_link_color',
    'profile_sidebar_border_color',
    'profile_sidebar_fill_color',
    'profile_text_color'
]

for index, row in df_prof.iterrows():
    pbc = str(row['profile_background_color'])
    plc = str(row['profile_link_color'])
    psbc = str(row['profile_sidebar_border_color'])
    psfc = str(row['profile_sidebar_fill_color'])
    ptc = str(row['profile_text_color'])
    
    rgb1 = [int(pbc[0:2], 16) // 32, int(pbc[2:4], 16) // 32, int(pbc[4:6], 16) // 32]
    rgb2 = [int(plc[0:2], 16) // 32, int(plc[2:4], 16) // 32, int(plc[4:6], 16) // 32]
    rgb3 = [int(psbc[0:2], 16) // 32, int(psbc[2:4], 16) // 32, int(psbc[4:6], 16) // 32]
    rgb4 = [int(psfc[0:2], 16) // 32, int(psfc[2:4], 16) // 32, int(psfc[4:6], 16) // 32]
    rgb5 = [int(ptc[0:2], 16) // 32, int(ptc[2:4], 16) // 32, int(ptc[4:6], 16) // 32]
    
    color_feat.append(sum([rgb1, rgb2, rgb3, rgb4, rgb5], []))
    color_feat_abl_pbc.append(sum([rgb2, rgb3, rgb4, rgb5], []))
    color_feat_abl_plc.append(sum([rgb1, rgb3, rgb4, rgb5], []))
    color_feat_abl_psbc.append(sum([rgb1, rgb2, rgb4, rgb5], []))
    color_feat_abl_psfc.append(sum([rgb1, rgb2, rgb3, rgb5], []))
    color_feat_abl_ptc.append(sum([rgb1, rgb2, rgb3, rgb4], []))

color_feat = np.array(color_feat)
print('All color:', color_feat)
color_feat_abl_pbc = np.array(color_feat_abl_pbc)
print('Ablation background_color:', color_feat_abl_pbc)
color_feat_abl_plc = np.array(color_feat_abl_plc)
print('All link_color:', color_feat_abl_plc)
color_feat_abl_psbc = np.array(color_feat_abl_psbc)
print('All sidebar_border_color:', color_feat_abl_psbc)
color_feat_abl_psfc = np.array(color_feat_abl_psfc)
print('All sidebar_fill_color:', color_feat_abl_psfc)
color_feat_abl_ptc = np.array(color_feat_abl_ptc)
print('All text_color:', color_feat_abl_ptc)

All color: [[1 1 1 6 1 2 4 4 2 4 6 1 1 2 0]]
Ablation background_color: [[6 1 2 4 4 2 4 6 1 1 2 0]]
All link_color: [[1 1 1 4 4 2 4 6 1 1 2 0]]
All sidebar_border_color: [[1 1 1 6 1 2 4 6 1 1 2 0]]
All sidebar_fill_color: [[1 1 1 6 1 2 4 4 2 1 2 0]]
All text_color: [[1 1 1 6 1 2 4 4 2 4 6 1]]


## Bio

In [18]:
# extraction

bio_feat_bow = []
bio_feat_bow_stop = []
bio_feat_fasttext = []
bio_feat_fasttext_mei = []
bio_feat_w2v = []

for d in df_prof['bio'].fillna(''):
    bio_feat_bow.append(d)
    tokens = nltk.word_tokenize(d)
    vec_sum_ft = np.zeros(ft.vector_size)
    vec_sum_ft_mei = np.zeros(ft_mei.vector_size)
    vec_sum_w2v = np.zeros(w2v.vector_size)
    
    tokens_stop = []
    
    for t in tokens:
        t = t.lower()
        
        try:
            vec_sum_ft += ft.wv[t]
        except:
            pass
        
        try:
            vec_sum_ft_mei += ft_mei.wv[t]
        except:
            pass
        
        try:
            vec_sum_w2v += w2v[t]
        except:
            pass
        
        if t not in stopword_set:
            tokens_stop.append(t)

    bio_feat_bow_stop.append(' '.join(tokens_stop))
    if len(tokens) > 0:
        vec_sum_ft = vec_sum_ft / len(tokens)
        vec_sum_ft_mei = vec_sum_ft_mei / len(tokens)
        vec_sum_w2v = vec_sum_w2v / len(tokens)
        
    bio_feat_fasttext.append(vec_sum_ft)
    bio_feat_fasttext_mei.append(vec_sum_ft_mei)
    bio_feat_w2v.append(vec_sum_w2v)
print(bio_feat_bow)
print(bio_feat_bow_stop)
print(bio_feat_fasttext)
print(bio_feat_fasttext_mei)
print(bio_feat_w2v)

['Governor of West Java. Broadcaster of Daily Happiness']
['governor of west java . broadcaster of daily happiness']
[array([ 2.29616454e-01,  2.32022300e-01, -4.72580629e-02,  3.54557215e-01,
        2.72061665e-01, -1.98238861e-01,  1.20082080e-01, -1.08769054e-01,
        9.88081050e-02,  9.92208214e-02,  1.93553222e-01, -4.42743142e-01,
        2.50536754e-01, -5.49882320e-02, -1.01235192e-01,  1.51985202e-01,
       -1.23445698e-01,  1.10331275e-01,  3.58676239e-02, -1.87953790e-01,
       -5.09244887e-03, -1.28359731e-01,  1.07102009e-01,  6.22490558e-02,
        1.23398944e-01, -3.96360084e-02, -1.37843834e-01, -1.94239910e-01,
       -4.38940442e-01,  1.97295624e-01, -2.43775972e-01, -1.88601344e-01,
       -8.34941119e-02,  1.19577813e-01,  2.71851562e-01, -2.33857926e-01,
       -1.03493498e-01, -2.69012964e-01, -1.21924798e-01, -3.14339507e-01,
        1.60772656e-01, -2.51501328e-01,  1.90861596e-01, -1.12338199e-03,
        1.65192808e-02,  1.53651417e-01, -1.45785145e-01,

In [19]:
# vectorization

bio_feat_bow_vec = get_vec(bio_feat_bow_vectorizer, bio_feat_bow)
bio_feat_bow_stop_vec = get_vec(bio_feat_bow_stop_vectorizer, bio_feat_bow_stop)

print(bio_feat_bow_vec)
print(bio_feat_bow_stop_vec)

[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]


## Name

Ia. Tokenize the name into bag of words

Ib. Use only first name

Ic. Parse name into first name, middle name, and last name <br>
If the name is more than 3 words, middle name has more than one value <br>
If the name is only one words, both middle and last names are null values <br>

In [6]:
# get name dictionary

endpoint_url = 'https://query.wikidata.org/sparql'

query = '''SELECT ?item ?itemLabel ?sexLabel
WHERE {
  ?item wdt:P31 wd:Q5 .
  ?item wdt:P27 wd:Q252 .
  ?item wdt:P21 ?sex .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "id, en". }
}'''

results = get_wikidata_dict(endpoint_url, query)

df_wikidata = pd.DataFrame()
for index, row in pd.DataFrame(results['results']['bindings']).iterrows():
    nama = row['itemLabel']['value']
    gender = row['sexLabel']['value']

    df_wikidata = df_wikidata.append({
        'nama': nama,
        'gender': gender
    }, ignore_index=True)
    
df_wikidata = df_wikidata.drop_duplicates()
display(df_wikidata['gender'].value_counts(dropna=False))
display(df_wikidata.head(1))

tokens_pria = get_name_tokens(df_wikidata, 'laki-laki')
print(len(tokens_pria))
display(tokens_pria[0:5])

tokens_wanita = get_name_tokens(df_wikidata, 'perempuan')
print(len(tokens_wanita))
display(tokens_wanita[0:5])

laki-laki                24742
perempuan                12390
perempuan transgender        7
Name: gender, dtype: int64

gender               nama
0  perempuan  Annemarie Madison

21164


['nayato', 'o.f.p', 'sumendap', 'bwan', 'hadrean']

13243


['rosdiyana', 'ebisawa', 'alimah', 'ayuningsih', 'pical']

In [7]:
# extraction

arr_name = []
dict_name = []

arr_first_name = []
dict_first_name = []

arr_first_name_alt = []
dict_first_name_alt = []
arr_middle_name = []
dict_middle_name = []
arr_last_name = []
dict_last_name = []

for d in df_prof['name']:
    d = d.lower()
    tokens = nltk.word_tokenize(d)
    
    contains_stopword = len(set(tokens) & (stopword_set - set(['dini', 'hari']))) > 0
    if re.sub(r'[\.\s\'\_\(\)\-\|\/\@]', '', d).isalpha() and not contains_stopword:
        arr_name.append(d)
        arr_first_name.append(' '.join(tokens[0:-1]))
        if len(tokens) >= 3:
            arr_first_name_alt.append(tokens[0])        
            arr_last_name.append(tokens[-1])
            arr_middle_name.append(' '.join(tokens[1:-1]))
        elif len(tokens) == 2:
            arr_first_name_alt.append(tokens[0])
            arr_middle_name.append('')
            arr_last_name.append(tokens[-1])
        else:
            arr_first_name_alt.append(tokens[0])
            arr_middle_name.append('')
            arr_last_name.append('')

        count_pria = 0
        count_wanita = 0
        
        count_pria_first = 0
        count_wanita_first = 0

        count_pria_first_alt = 0
        count_wanita_first_alt = 0

        count_pria_middle = 0
        count_wanita_middle = 0

        count_pria_last = 0
        count_wanita_last = 0

        for t in range(len(tokens)):
            if t == 0:
                if tokens[t] in tokens_pria:
                    count_pria_first += 1
                    count_pria_first_alt += 1
                elif tokens[t] in tokens_wanita:
                    count_wanita_first += 1
                    count_wanita_first_alt += 1
                    
            elif t == len(tokens) - 1:
                if tokens[t] in tokens_pria:
                    count_pria_last += 1
                elif tokens[t] in tokens_wanita:
                    count_wanita_last += 1
                    
            else:
                if tokens[t] in tokens_pria:
                    count_pria_first += 1
                    count_pria_middle += 1
                elif tokens[t] in tokens_wanita:
                    count_wanita_first += 1
                    count_wanita_middle += 1
            
            if tokens[t] in tokens_pria:
                count_pria += 1
            elif tokens[t] in tokens_wanita:
                count_wanita += 1
        dict_name.append([count_pria, count_wanita])
        dict_first_name.append([count_pria_first, count_wanita_first])
        dict_first_name_alt.append([count_pria_first_alt, count_wanita_first_alt])
        dict_middle_name.append([count_pria_middle, count_wanita_middle])
        dict_last_name.append([count_pria_last, count_wanita_last])
        
    else:
        arr_name.append('')
        arr_first_name.append('')
        arr_first_name_alt.append('')
        arr_middle_name.append('')
        arr_last_name.append('')
        dict_name.append([0, 0])
        dict_first_name.append([0, 0])
        dict_first_name_alt.append([0, 0])
        dict_middle_name.append([0, 0])
        dict_last_name.append([0, 0])

arr_name = np.array(arr_name) 
dict_name = np.array(dict_name)

arr_first_name = np.array(arr_first_name)
dict_first_name = np.array(dict_first_name)

arr_first_name_alt = np.array(arr_first_name_alt) 
dict_first_name_alt = np.array(dict_first_name_alt)

arr_middle_name = np.array(arr_middle_name) 
dict_middle_name = np.array(dict_middle_name)

arr_last_name = np.array(arr_last_name)
dict_last_name = np.array(dict_last_name)

print(arr_name, dict_name)
print(arr_first_name, dict_first_name)
print(arr_first_name_alt, dict_first_name_alt)
print(arr_middle_name, dict_middle_name)
print(arr_last_name, dict_last_name)

['ridwan kamil'] [[2 0]]
['ridwan'] [[1 0]]
['ridwan'] [[1 0]]
[''] [[0 0]]
['kamil'] [[1 0]]


In [8]:
# vectorization

ia = get_vec(name_feat_ia_vectorizer, arr_name)
ib = get_vec(name_feat_ib_vectorizer, arr_first_name)

ic_first_name_alt = get_vec(name_feat_ic_first_vectorizer, arr_first_name_alt)
ic_middle_name = get_vec(name_feat_ic_middle_vectorizer, arr_middle_name)
ic_last_name = get_vec(name_feat_ic_last_vectorizer, arr_last_name)

ic = np.hstack((ic_first_name_alt, ic_middle_name, ic_last_name))

print(ia)
print(ib)
print(ic)

# concate with name dict feature

ia_with_dict = np.hstack((ia, dict_name))
ib_with_dict = np.hstack((ib, dict_first_name))
ic_train_with_dict = np.hstack((ic_first_name_alt, dict_first_name_alt, ic_middle_name, dict_middle_name, ic_last_name, dict_last_name))

print(ia_with_dict)
print(ib_with_dict)
print(ic_train_with_dict)

[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 2 0]]
[[0 0 0 ... 0 1 0]]
[[0 0 0 ... 0 1 0]]


## Username

In [9]:
# vectorization

arr_ids = np.array([re.sub(r'\d+', '', d) for d in df_prof['username']])
username_feat_bow = get_vec(username_feat_bow_vectorizer, arr_ids)
username_feat_char = get_vec(username_feat_char_vectorizer, arr_ids)

print(username_feat_bow)
print(username_feat_char)

[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]


## Network

In [10]:
# extraction

likes_count = df_tweet[df_tweet['likes_count'] > 0].shape[0] / df_tweet.shape[0]
retweets_count = df_tweet[df_tweet['retweets_count'] > 0].shape[0] / df_tweet.shape[0]

print(np.hstack((df_prof['followers'], df_prof['friends_count'], df_prof['listed_count'], df_prof['favourites_count'], likes_count, retweets_count)))

[4.974848e+06 2.842000e+03 1.547000e+03 2.203700e+04 1.000000e+00
 1.000000e+00]


## Behavior

In [11]:
# extraction

mention = df_tweet[df_tweet.mentions != '[]'].shape[0] / df_tweet.shape[0]
hashtags = df_tweet[df_tweet.hashtags != '[]'].shape[0] / df_tweet.shape[0]
photos = df_tweet[df_tweet.photos != '[]'].shape[0] / df_tweet.shape[0]
video = df_tweet[df_tweet.video == 1].shape[0] / df_tweet.shape[0]
days = df_tweet.groupby('date')['tweet'].nunique().mean()

print(np.hstack((mention, hashtags, photos, video, days)))

[0.06666667 0.41666667 0.41666667 0.83333333 2.85714286]


## Socio

In [14]:
# extraction

word_count_sum = 0
char_count_sum = 0
repeated_alphabets_sum = 0
ellipses_sum = 0
exclamation_sum = 0
upper_words_sum = 0
capitalized_words_sum = 0 
emoticon_sum = 0
adjective_sum = 0
noun_sum = 0
verb_sum = 0

for t in df_tweet['tweet']:
    token = nltk.word_tokenize(t)
    word_count_sum += len(token)
    char_count_sum += len(t)
    repeated_alphabets_sum += len(re.findall(r'([A-Za-z])\1\1', t))
    ellipses_sum += len(re.findall(r'([.])\1', t))
    exclamation_sum += len(re.findall(r'([!])\1', t))

    for w in token:
        if w.isupper():
            upper_words_sum += 1
        if w.istitle():
            capitalized_words_sum += 1

    for e in emoticons:
        emoticon_sum += t.count(e)

    tag = ct.tag_sents([token])
    flat_tag = [item for sublist in tag for item in sublist]
    pos_count = Counter([j for i, j in flat_tag])
    adjective_sum += pos_count['JJ']
    verb_sum += pos_count['VB']
    noun_sum += pos_count['NN']
    
print(np.hstack((word_count_sum, char_count_sum, repeated_alphabets_sum, ellipses_sum, exclamation_sum, upper_words_sum, capitalized_words_sum, emoticon_sum, adjective_sum, noun_sum, verb_sum)))

[ 2503 15250     0     0     0    39   437     0    68   596   270]


## Tweet

In [22]:
# extraction

tweet_feat_bow = []
tweet_feat_bow_stop = []
tweet_feat_fasttext = []
tweet_feat_fasttext_mei = []
tweet_feat_w2v = []

d = ' '.join(df_tweet['tweet'])

tweet_feat_bow.append(d)
tokens = nltk.word_tokenize(d)
vec_sum_ft = np.zeros(ft.vector_size)
vec_sum_ft_mei = np.zeros(ft_mei.vector_size)
vec_sum_w2v = np.zeros(w2v.vector_size)

tokens_stop = []

for t in tokens:
    t = t.lower()

    try:
        vec_sum_ft += ft.wv[t]
    except:
        pass

    try:
        vec_sum_ft_mei += ft_mei.wv[t]
    except:
        pass

    try:
        vec_sum_w2v += w2v[t]
    except:
        pass

    if t not in stopword_set:
        tokens_stop.append(t)

tweet_feat_bow_stop.append(' '.join(tokens_stop))
if len(tokens) > 0:
    vec_sum_ft = vec_sum_ft / len(tokens)
    vec_sum_ft_mei = vec_sum_ft_mei / len(tokens)
    vec_sum_w2v = vec_sum_w2v / len(tokens)

tweet_feat_fasttext.append(vec_sum_ft)
tweet_feat_fasttext_mei.append(vec_sum_ft_mei)
tweet_feat_w2v.append(vec_sum_w2v)

print(tweet_feat_bow)
print(tweet_feat_bow_stop)
print(tweet_feat_fasttext)
print(tweet_feat_fasttext_mei)
print(tweet_feat_w2v)

['Semoga Qurban dan segala pengorbanan kita semua ini diterima Allah SWT sebagai pahala yang menyelamatkan kita di akhir waktu kelak.  Kami haturkan mohon maaf lahir dan bathin juga.  Hatur nuhun.  https://t.co/BF9obneb2P Alhamdulillah, semua proses badal haji atau menghajikan atas nama Eril sudah kami tunaikan. Dari niat sampai proses wajib rukun dan sunnahnya.  Semoga menjadi Haji Mabrur.  SELAMAT IDUL ADHA 1443 H, juga kami haturkan kepada umat Islam yang merayakan. Mohon maaf lahir batin.  https://t.co/cnk7kA0XQy Suasana Indonesia di Tanah Suci.  Ketika mengecek kondisi para jamaah, ternyata serasa di kampung sendiri, saat di Mekkah berjumpa dengan yang dirindukan melebihi ke istri sendiri yaitu the one and only: BALA-BALA.   #JabarJuara #IndonesiaJuara  https://t.co/i9veC88CjL Insya Allah, pulang ke tanah air tetap dengan predikat Hajjah yang menyempurnakan rukun islam ke-5 nya.  Bersyukurlah saat mendapat keberkahan. Bersabarlah sat mendapat kemusibahan. Berikhtiarlah saat kita m

In [23]:
# vectorization

tweet_feat_bow_vec = get_vec(tweet_feat_bow_vectorizer, tweet_feat_bow)
tweet_feat_bow_stop_vec = get_vec(tweet_feat_bow_stop_vectorizer, tweet_feat_bow_stop)

print(tweet_feat_bow_vec)
print(tweet_feat_bow_stop_vec)

[[2 1 0 ... 0 0 0]]
[[2 1 0 ... 0 0 0]]
